### ISSUE TITLE
 Excuse me, when will the training code be released

### ISSUE THREAD

**Issue by momohuangsha** [whwu95/ATM#1]
Congratulations on ATM being approved by iccv.
Excuse me, when will the training code be released?

**Comment by JinxiaXie** [comment]
if so, please let me known.

**Comment by whwu95** [comment]
I will release the code before the ICCV conference, around the end of September. I've been quite busy recently and haven't had the chance to organize it yet.

**Comment by erictang000** [comment]
Hi, just checking in again on the training code release! Would be super helpful for a project I'm currently working on. Thanks!

**Comment by whwu95** [comment]
> I will release the code before the ICCV conference, around the end of September. I've been quite busy recently and haven't had the chance to organize it yet.



I'm sorry for the delay. I've been busy working on other submissions and dealing with various miscellaneous matters recently, so I haven't had time to organize the code. I anticipate that it will be open-sourced in the mid of November.

**Comment by whwu95** [comment]
Hello everyone, I apologize for the delay, but the training code for ATM has now been released！
